### ISSUE TITLE
Interesting, but can you give a concrete example?

### ISSUE THREAD

**Issue by rajaraodv** [Mitranim/posterus#1]
I understand that it's probably a very big deal to be able to cancel. But can you show and prove it with a concrete example?

**Comment by Mitranim** [comment]
Apologies for being slow, getting my thoughts in order. There's a lot to add to the docs after the HN discussion.

**Comment by Mitranim** [comment]
Added a writeup on "why cancelation". Incidentally, it also talks about other reasons that motivated the design:

https://github.com/Mitranim/posterus/blob/39687b21c94fe7e148381ab90c03ba07f3ae0a45/readme.md#why
