### ISSUE TITLE
Cancellation does propagate upstream

### ISSUE THREAD

**Issue by petkaantonov** [Mitranim/posterus#2]
> Here's an example: in Bluebird, cancelation doesn't propagate upstream. After registering onCancel in a promise constructor, you have to call .cancel() on that exact promise object. Calling .cancel() in any child promise created with .then() or .catch() will not abort the work, rendering the feature useless for the most common use case!

This is not true at all. See for example this test: https://github.com/petkaantonov/bluebird/blob/master/test/mocha/cancel.js#L172-L195 Read that entire file to see how many use cases promise cancellation can work with.

**Comment by Mitranim** [comment]
Yes, thank you for correcting me. People have already pointed this out on HN. Pretty sure this is a new feature; didn't work last time I checked, which was a few months ago, but it works now, which is great. I'll post the updated readme in a few days.

**Comment by Mitranim** [comment]
Corrected. Sorry it took so long. Writing philosophy takes a lot of energy.

Incidentally, I added writeups on philosophical differences, such as why unicast vs broadcast, why not Bluebird or Rx, and so on. Don't know if you care, but: https://github.com/Mitranim/posterus/blob/39687b21c94fe7e148381ab90c03ba07f3ae0a45/readme.md#why
