### ISSUE TITLE
build is minified, posterus methods don't work

### ISSUE THREAD

**Issue by scott-cornwell** [Mitranim/posterus#3]
If I just install and import { Future } from posterus, I can't actually use it. I get an error that complains future.settle is not a function. Looking at the future object the methods are all one letter. I checked out your gulp file and it uses uglify with mangle: false, but apparently that still mangles your methods. I would think removing the uglify would be better.

**Comment by Mitranim** [comment]
Thanks for using Posterus! I'm glad you find it useful.

`package.json` points to the non-minified `dist/posterus`. None of my build tools resolve this to the minified file, so this comes as a surprise. The minified versions exist only for evaluating the minified code size, so I should probably exclude them from the distribution. Thanks for the suggestion!

**Comment by Mitranim** [comment]
Done! Please install `0.2.1` and check.

**Comment by scott-cornwell** [comment]
Hey, thanks for the quick response. Turns out I was wrong, the single letter properties are actually in the code. For some reason the settle method is missing though. I'm using posterus with webpack, babel and react. I will try to investigate further and hopefully put up a repro somewhere if I can't figure it out.

**Comment by Mitranim** [comment]
The build intentionally minifies "private" properties to reduce the size (I care about that a lot). Also simplifies the API surface. Public stuff, including `settle`, is not mangled. However, `settle` was renamed 9 weeks ago. Might wanna check if you're using a recent version.

**Comment by scott-cornwell** [comment]
Ah ok, maybe just a case of docs needing to be updated, the readme still has references to settle. What was it renamed to?

**Comment by Mitranim** [comment]
Edited the comment for clarity, see above.

**Comment by scott-cornwell** [comment]
Ah nevermind, I get it, I think I was using an old version through DllPLugin!

**Comment by Mitranim** [comment]
Does it work now?

**Comment by scott-cornwell** [comment]
Yeah got it working, thanks!
